### ISSUE TITLE
Allow multiple sequences per model

### ISSUE THREAD

**Issue by pixelvitamina** [djreimer/sequenced#18]
Use case:

```ruby
class Order < ActiveRecord::Base
  belongs :cart 
  acts_as_sequenced column: :sequence
  acts_as_sequenced column: :per_cart_sequence, scope: :cart_id
end
```
Issue: 

`per_cart_sequence` will overwrite the `sequence` options, and we and having only one sequence triggered

**Comment by mopx** [comment]
@pixelvitamina I'm trying to do the same, did you found an alternative?

**Comment by djreimer** [comment]
This would be handy. It shouldn't be too terribly difficult to support. I'll try to dig into this soon - PRs welcome too if anyone wants to take a stab at implementing.

**Comment by samphilipd** [comment]
@mopx @pixelvitamina see latest master.

@djreimer This issue can be closed now right?

**Comment by djreimer** [comment]
@samphilipd yep!

**Comment by pixelvitamina** [comment]
@samphilipd great, thanks!
