### ISSUE TITLE
NoMethodError calling any? on sequenced_options under 3.1.0

### ISSUE THREAD

**Issue by ninjarobert** [djreimer/sequenced#21]
I get a Runtime error on line 55 https://github.com/djreimer/sequenced/blob/master/lib/sequenced/acts_as_sequenced.rb#L55

It appears at this point, sequenced_options is nil. If I fall back to 3.0.0, my app runs fine.

My app is running under Ruby 2.1.7 and Rails 3.2 currently.

**Comment by djreimer** [comment]
Is this something you ran into @samphilipd?

**Comment by samphilipd** [comment]
@djreimer no... let me try to reproduce and I'll get back to you.

**Comment by samphilipd** [comment]
@djreimer OK I know why this is happening. It seems that the `mattr_accessor` method changed in Rails 4.

In 3.2 it does not use the block to set the default argument. If we want to continue supporting Rails 3.2, the attached pull request will probably fix it.

**Comment by djreimer** [comment]
Should be fixed now! Released v3.1.1.
