### ISSUE TITLE
Suggestions for migrating existing models with rows?

### ISSUE THREAD

**Issue by dagumak** [djreimer/sequenced#28]
I have an existing model and a set of data that I would like to number. What's the best way to migrate all of those and to ensure that all existing data has a number based on its creation order?

**Comment by djreimer** [comment]
There are number of ways you could go about it. Something like this should work pretty well for PostgreSQL (syntax of the update statement may vary for other DB systems).

1. Add sequenced to your model deploy it.
2. Re-index the `sequential_id` column on your existing records:

    ```
    UPDATE posts SET sequential_id = row_number
    FROM (
      SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) AS row_number
      FROM posts
    ) p2
    WHERE posts.id = p2.id
    ```

You can manipulate the window function to support scoped sequential IDs. For example,

```
ROW_NUMBER() OVER (partition BY account_id ORDER BY created_at ASC)
```
